# Generated by Django 4.2.7 on 2024-01-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_contact_remove_reservation_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="num_persons",
            field=models.PositiveIntegerField(),
        ),
    ]
