# Generated by Django 4.2.7 on 2024-01-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_reservation_num_persons"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="time",
            field=models.TimeField(null=True),
        ),
    ]
