# Generated by Django 5.0.1 on 2024-02-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_reservation_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="email",
        ),
    ]
