# Generated by Django 5.0.1 on 2024-02-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_reservation_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(verbose_name="Дата посещения"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="num_persons",
            field=models.PositiveIntegerField(verbose_name="Количество человек"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="phone",
            field=models.CharField(
                default="0", max_length=15, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(null=True, verbose_name="Время посещения"),
        ),
    ]
