# Generated by Django 5.0.1 on 2024-01-29 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_dish_category_alter_dish_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="menu.category",
            ),
        ),
    ]
