# Generated by Django 5.0.1 on 2024-01-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_alter_dish_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",)},
        ),
    ]
