# Generated by Django 5.0.1 on 2024-02-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0009_alter_category_options_alter_dish_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(max_length=130, verbose_name="Описание"),
        ),
    ]
